version: 2
jobs:
  build:
    docker:
      - image: bepsays/ci-goreleaser
    working_directory: /go/src/github.com/gohugoio/hugo
    steps:
      - checkout
      - run:
            command: |
                git config --global user.email "deploy@gohugo.io"
                git config --global user.name "hugobot"
                git clone https://github.com/gohugoio/hugoDocs.git
                make vendor
                go run -tags release main.go release -r ${CIRCLE_TAG}
workflows:
  version: 2
  release:
      jobs:
        - build:
            context: org-global
            filters:
              tags:
                only: /v[0-9]+(\.[0-9]+)*(-.*)*test$/
              branches:
                ignore: /.*/
